### ISSUE TITLE
Guidance for mujoco and minigrid

### ISSUE THREAD

**Issue by Acedorkz** [YimingWangMingle/EME#1]
Hi, this is an interesting work. Could u please provide the code and guidance for how to run on mujoco and minigrid. It is a great help for reproducing the experimental results of mujoco and minigrid. Thanks and have a nice day.

**Comment by start6666666** [comment]
![Image](https://github.com/user-attachments/assets/d1dbb9bc-683c-4fc7-8f57-ae5b442610be)Hello author, I would like to ask whether the advantages calculated by the ppo_update method in the eme_train.py file are finally used in the update of the PPO algorithm? What is its function?

**Comment by KaiyanZhaoPhoenix** [comment]
After a quick review of the code, it seems that the update for the recalculated advantage was inadvertently removed during code cleanup. I’ll fix it shortly, thanks~

**Comment by start6666666** [comment]
> After a quick review of the code, it seems that the update for the recalculated advantage was inadvertently removed during code cleanup. I’ll fix it shortly, thanks~

Thank you very much, your method is very interesting!
